name: Gitleaks Secrets Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  gitleaks:
    name: Run Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "--verbose --redact"
        env:    
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
