name: Gitleaks Secrets Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] # Ensure this is also set for PRs targeting main

jobs:
  gitleaks:
    name: Run Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Good, this is correct for full history

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        # Correct placement for environment variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Uncomment if you have an organizational license

        # Correct placement for action-specific parameters
        with:
          # Arguments to pass directly to the gitleaks binary
          # args: "--verbose --redact"
          
          # Enable PR comments for Gitleaks findings (defaults to true if GITHUB_TOKEN is present)
          # Explicitly setting it ensures it's clear.
          GITLEAKS_ENABLE_COMMENTS: 'true' 

          # Upload a SARIF report for GitHub Code Scanning alerts
          # This will show up in the 'Security' tab of your repo
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: 'false'
